emission_budget_levels:
  - identifier: bronze
    name: Pronssi
    carbon_footprint: 1100
    year: 2021
  - identifier: silver
    name: Hopea
    carbon_footprint: 800
    year: 2021
  - identifier: gold
    name: Kulta
    carbon_footprint: 550
    year: 2021

transport_modes:
  - identifier: still
    name: Paikoillaan
    name_en: Still
    emission_factor: 0
  - identifier: walk
    name: Kävely
    name_en: Walking
    emission_factor: 0
  - identifier: bicycle
    name: Pyöräily
    name_en: Bicycling
    emission_factor: 5
  - identifier: car
    name: Henkilöauto
    name_en: Car
    emission_factor: 185.6
    variants:
      - identifier: small_ice
        name: Polttomoottoriauto (pieni)
        name_en: Combustion engine (small)
        emission_factor: 151.2
      - identifier: average_ice
        name: Polttomoottoriauto (keskikokoinen)
        name_en: Combustion engine (keskikokoinen)
        emission_factor: 185.6
      - identifier: large_ice
        name: Polttomoottoriauto (suuri)
        name_en: Combustion engine (suuri)
        emission_factor: 203.3
      - identifier: hybrid
        name: Hybridi
        name_en: Hybrid
        emission_factor: 120
      - identifier: bev
        name: Täyssähkö
        name_en: Battery electric
        emission_factor: 55.4
      - identifier: gas
        name: Kaasu
        name_en: Natural gas
        emission_factor: 53.2
  - identifier: bus
    name: Bussi
    name_en: Bus
    emission_factor: 63.2
  - identifier: tram
    name: Ratikka
    name_en: Tram
    emission_factor: 5.6
  - identifier: train
    name: Juna
    name_en: Train
    emission_factor: 5.2
  - identifier: other
    name: Muu
    name_en: Other
    emission_factor: 5
    variants:
      - identifier: rollerskates
        name: Rullaluistimet
        name_en: Roller skates
        emission_factor: 0
      - identifier: skateboard
        name: Skeittilauta
        name_en: skateboard
        emission_factor: 0
      - identifier: escooter
        name: Sähköpotkulauta
        name_en: Electric scooter
        emission_factor: 7
      - identifier: other
        name: Muu
        name_en: Other
        emission_factor: 5
